
mobs:register_mob("gtmobs:ent", {
	type = "npc",
	hp_min = 50,
	hp_max = 70,
	collisionbox = {-1.8, -0.02, -1.4, 1.4, 5.2, 1.4},
	textures = {
		"default_dirt.png",
	},
	visual_size = {x=3.5,y=3.5},
	visual = "mesh",
	mesh = "ent_model.x",
	view_range = 20,
	makes_footstep_sound = true,
	walk_velocity = 1,
     run_velocity = 1,
	armor = 100,
	damage = 5,
	drops = {
		{name = "default:tree",
		chance = 10,
		min = 5,
		max = 10,},
	},
	light_resistant = true,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 60,
	light_damage = 0,
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 17,
		stand_end = 17,
		walk_start = 10,
		walk_end = 80,
		run_start = 10,
		run_end = 80,
		punch_start = 10,
		punch_end = 80,
	},
	jump = true,
	sounds = {},
	attacks_monsters = true,
	peaceful = true,
	group_attack = true,
	step = 1,

})
mobs:register_spawn("gtmobs:ent", {"glowtest:tree"}, 20, -1, 200, 3, 31000)
